import { eiken4CoreExamQuestions } from '../data/eiken4Curriculum';
import { getLocalDate } from './eiken4ProgressService';
const KEY='eiken4ExamPracticeV1';
const WEAK_KEY='eiken4ExamWeakV1';
const hash=(s:string)=>{let n=0;for(const c of s)n=(Math.imul(n,31)+c.charCodeAt(0))|0;return n>>>0;};
const loadWeak=():Record<string,number>=>{if(typeof localStorage==='undefined')return{};try{return JSON.parse(localStorage.getItem(WEAK_KEY)||'{}')}catch{return{}}};
export const getDailyExamQuestions=()=>{const weak=loadWeak();return eiken4CoreExamQuestions.map((q,i)=>({q,n:hash(`${getLocalDate()}-${i}`),weak:weak[q.id]||0})).sort((a,b)=>b.weak-a.weak||a.n-b.n).slice(0,10).map(x=>x.q)};
export const recordExamAnswer=(id:string,correct:boolean)=>{if(typeof localStorage==='undefined')return;const weak=loadWeak();weak[id]=correct?Math.max(0,(weak[id]||0)-1):Math.min(9,(weak[id]||0)+2);localStorage.setItem(WEAK_KEY,JSON.stringify(weak));};
export type ExamPracticeResult={date:string;answers:Record<string,string>;completedAt?:string};
export const loadExamPractice=():ExamPracticeResult=>{if(typeof localStorage==='undefined')return{date:getLocalDate(),answers:{}};try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?.date===getLocalDate()?x:{date:getLocalDate(),answers:{}};}catch{return{date:getLocalDate(),answers:{}}}};
export const saveExamPractice=(x:ExamPracticeResult)=>{if(typeof localStorage!=='undefined')localStorage.setItem(KEY,JSON.stringify(x));};
