import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Button from '../components/Button';
import ArrowLeftIcon from '../components/shared/ArrowLeftIcon';
import SpeakerWaveIcon from '../components/shared/SpeakerWaveIcon';
import { getFullMock, saveFullMockResult } from '../services/eiken4ExamPrepService';
import { speakText } from '../services/speechService';

const Eiken4FullMockPage: React.FC = () => {
  const navigate = useNavigate(); const questions = useMemo(() => getFullMock(), []); const startedAt = useRef(Date.now());
  const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [selected, setSelected] = useState(''); const [answers, setAnswers] = useState<Record<string,string>>({}); const [finished, setFinished] = useState(false); const [remaining,setRemaining]=useState(65*60);
  const current = questions[index];
  const finishMock = (answerMap: Record<string,string>) => { const reading = questions.slice(0,35).filter(q => answerMap[q.id] === q.answer).length; const listening = questions.slice(35).filter(q => answerMap[q.id] === q.answer).length; saveFullMockResult({ id: new Date().toISOString(), date: new Date().toLocaleDateString('ja-JP'), reading, listening, readingTotal:35, listeningTotal:30, timeUsed:Math.round((Date.now()-startedAt.current)/1000) }); setFinished(true); };
  useEffect(()=>{if(!started||finished)return;const timer=window.setInterval(()=>setRemaining(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[started,finished]);
  useEffect(()=>{if(started&&!finished&&remaining===0)finishMock(answers)},[remaining,started,finished]);
  const next = () => { const updated = { ...answers, [current.id]: selected }; setAnswers(updated); setSelected(''); if (index < questions.length - 1) setIndex(index + 1); else finishMock(updated); };
  if (!started) return <div className="flex-grow bg-slate-50 p-4"><div className="mx-auto max-w-xl"><Button onClick={()=>navigate('/eiken4')} variant="ghost" size="sm"><ArrowLeftIcon className="mr-2 h-5 w-5"/>戻る</Button><section className="mt-5 rounded-3xl bg-white p-7 text-center shadow"><p className="font-bold text-rose-600">本番と同じ問題数</p><h1 className="mt-2 text-3xl font-extrabold">英検4級 フル模試</h1><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-rose-50 p-4"><b className="text-2xl">35問</b><p className="text-sm">リーディング</p></div><div className="rounded-2xl bg-indigo-50 p-4"><b className="text-2xl">30問</b><p className="text-sm">リスニング</p></div></div><p className="mt-5 text-sm text-slate-500">目安65分。途中で答えは表示されません。</p><Button onClick={()=>{startedAt.current=Date.now();setStarted(true)}} size="lg" className="mt-6 w-full rounded-2xl bg-rose-600">模試を始める</Button></section></div></div>;
  if (finished) { const reading=questions.slice(0,35).filter(q=>answers[q.id]===q.answer).length; const listening=questions.slice(35).filter(q=>answers[q.id]===q.answer).length; return <div className="flex-grow bg-slate-50 p-4"><section className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-7 text-center shadow"><p className="font-bold text-emerald-600">フル模試完了</p><h1 className="mt-2 text-4xl font-extrabold">{reading+listening} / 65</h1><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-rose-50 p-3">読解 <b>{reading}/35</b></div><div className="rounded-xl bg-indigo-50 p-3">聞く <b>{listening}/30</b></div></div><p className="mt-4 text-sm text-slate-500">両方75%以上を安定して取ることを目標にしよう。</p><Button onClick={()=>navigate('/eiken4')} className="mt-6 w-full">英検4級トップへ</Button></section></div>; }
  const listening = index >= 35;
  return <div className="flex-grow bg-slate-50 p-4"><div className="mx-auto max-w-2xl"><div className="flex justify-between text-sm font-bold"><span>{current.section}</span><span className={remaining<300?'text-rose-600':''}>残り {String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}　{index+1}/65</span></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-rose-500" style={{width:`${(index+1)/65*100}%`}}/></div><main className="mt-4 rounded-3xl bg-white p-5 shadow"><p className="text-sm text-slate-500">{current.detail}</p>{current.passage&&<p className="mt-4 rounded-xl bg-sky-50 p-4 leading-7">{current.passage}</p>}{listening&&<button onClick={()=>speakText(current.audioText||'', 'en-US', .82)} className="mt-4 flex w-full items-center justify-center rounded-xl bg-indigo-600 py-4 font-bold text-white"><SpeakerWaveIcon className="mr-2 h-5 w-5"/>音声を聞く</button>}<h1 className="mt-5 text-xl font-bold">{current.prompt}</h1><div className="mt-4 space-y-2">{current.choices.map((choice,i)=><button key={choice} onClick={()=>setSelected(choice)} className={`w-full rounded-xl border p-4 text-left font-bold ${selected===choice?'border-rose-400 bg-rose-50':'border-slate-200'}`}>{i+1}. {choice}</button>)}</div><Button disabled={!selected} onClick={next} size="lg" className="mt-5 w-full rounded-xl bg-rose-600">{index===64?'採点する':'次へ'}</Button></main></div></div>;
};
export default Eiken4FullMockPage;
